services:
  - type: web
    name: trading-analytics-platform
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
    healthCheckPath: /
    plan: free
